namespace: samdoran
name: testing
version: 1.0.1
readme: README.md
authors:
  - Sam Doran <sdoran@redhat.com>

description: Forks of modules from Ansible Core for testing

license:
  - GPL-2.0-or-later

tags:
  - development
  - system
  - ansible

dependencies: {}

repository: http://github.com/samdoran/ansible-collection-testing
documentation: http://github.com/samdoran/ansible-collection-testing/README.md
homepage: http://github.com/samdoran/ansible-collection-testing
issues: http://github.com/samdoran/ansible-collection-testing/issues

build_ignore: []
